/**
 * The committed seed block and the generator that produced it are the SAME
 * BYTES.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHAT THIS BUYS, AND WHY A GENERATOR NOBODY RE-RUNS WOULD BE WORSE THAN NO
 * GENERATOR AT ALL.
 *
 * Migration 0012 seeds ~800 places. They are generated from a checked-in dataset
 * because typing them is 768 chances to fat-finger a place name into a file that
 * can never be edited once it has run anywhere. But a generator whose output is
 * pasted in once and then diverges is the worst of both worlds: the migration
 * looks authoritative, the script looks like the source of truth, and neither is.
 *
 * So the block lives between two markers and this suite reproduces it. Change
 * the district list, the alias set or the dataset and this goes red until the
 * block is regenerated — `npx tsx scripts/gen-service-areas.ts`, paste, done.
 *
 * IT ALSO RE-RUNS EVERY INVARIANT THE GENERATOR ASSERTS, because those throws
 * fire at authoring time on one developer's machine and would otherwise be
 * checked by nobody after that.
 * ═══════════════════════════════════════════════════════════════════════════
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { DATASET, DISTRICTS, DISTRICT_REGION, areaId, areaKey, renderSeed, seedRows, slug } from './gen-service-areas';

const MIGRATION = 'server/db/migrations/0012_service_areas.sql';
const OPEN = '-- >>> generated by scripts/gen-service-areas.ts';
const CLOSE = '-- <<< generated';

const dataset = readFileSync(DATASET, 'utf8');

/** The committed block, sliced out of the migration exactly as the splice put
 *  it in: everything after the opening marker's newline, up to the closing
 *  marker, minus the single newline that separates them. */
function committedBlock(): string {
  const source = readFileSync(MIGRATION, 'utf8');
  const openAt = source.indexOf(OPEN);
  const closeAt = source.indexOf(CLOSE);
  expect(openAt).toBeGreaterThan(-1);
  expect(closeAt).toBeGreaterThan(openAt);
  return source.slice(source.indexOf('\n', openAt) + 1, closeAt).replace(/\n$/, '');
}

describe('the generated seed', () => {
  it('is byte-identical to what the generator produces today', () => {
    expect(committedBlock()).toBe(renderSeed(dataset));
  });

  it('is a single statement — no breakpoint may fall inside it', () => {
    /*
     * The runner splits on `--> statement-breakpoint`, so a breakpoint inside the
     * VALUES list would hand Postgres half an INSERT. It would also make a
     * partially-applied seed possible: some districts in the switcher and some
     * not, with nothing anywhere to say so.
     */
    const block = committedBlock();
    expect(block).not.toContain('statement-breakpoint');
    expect(block.match(/INSERT INTO/g)).toHaveLength(1);
    expect(block.trimEnd().endsWith('ON CONFLICT DO NOTHING;')).toBe(true);
  });

  it('carries every place in the dataset except the served region’s own LGAs', () => {
    const rows = seedRows(dataset);
    const source = JSON.parse(dataset) as Record<string, string[]>;
    const expected =
      Object.entries(source)
        .filter(([region]) => region !== DISTRICT_REGION)
        .reduce((n, [, names]) => n + names.length, 0) + DISTRICTS.length;

    expect(rows).toHaveLength(expected);
    /*
     * THE DROPPED SIX, NAMED. The served region's own LGAs are administrative
     * units and one of them contains every district on the board — seeding them
     * would put two overlapping answers to "where is this address" in one table.
     * Asserted by COUNT rather than by name so this does not become a second
     * place the dataset's spellings are written down.
     */
    expect(rows.filter((row) => row.region === DISTRICT_REGION)).toHaveLength(DISTRICTS.length);
    expect(source[DISTRICT_REGION]).toHaveLength(6);
  });

  it('ships exactly the served region active and everywhere else off', () => {
    const rows = seedRows(dataset);
    const active = rows.filter((row) => row.active);
    expect(active).toHaveLength(DISTRICTS.length);
    expect(new Set(active.map((row) => row.region))).toEqual(new Set([DISTRICT_REGION]));
    /* The whole failure-mode argument in one assertion: a row nobody thought
     * about is OFF, so the mistake costs a sale rather than a promise. */
    expect(rows.filter((row) => !row.active).every((row) => row.region !== DISTRICT_REGION)).toBe(true);
  });

  it('marks every seeded row as seeded, at revision 1', () => {
    // `seeded` is the ONLY thing the Areas screen's "shipped" marker may derive
    // from — matching on a key or a name is what the grep guards forbid — and
    // revision 1 is what a CAS PATCH must move off.
    const block = committedBlock();
    const rows = seedRows(dataset);
    expect(block.match(/, true, \d+, 1, /g)).toHaveLength(rows.length);
  });

  it('gives every row a unique, well-shaped key and id', () => {
    const rows = seedRows(dataset);
    // `marketing_service_areas_key_ck`, restated — the generator throws on a
    // violation, and this is what makes that throw reachable from the suite.
    for (const row of rows) expect(row.key).toMatch(/^[a-z0-9][a-z0-9_-]*$/);
    expect(new Set(rows.map((row) => row.key)).size).toBe(rows.length);
    expect(new Set(rows.map((row) => row.id)).size).toBe(rows.length);
    expect(rows.every((row) => row.id.startsWith('area_'))).toBe(true);
  });

  it('refuses two served areas that a customer could not tell apart', () => {
    /*
     * THE MUTATION THIS GUARD EXISTS FOR. The resolver folds case and
     * punctuation, then prefers an active row; two ACTIVE rows folding together
     * would leave it choosing by sort order between two places a van really goes
     * — a customer sent to the wrong board, silently.
     *
     * Driven by handing the generator a dataset that contains the collision,
     * rather than by asserting the guard's source: a check that is never made to
     * fire is a check that can be deleted with every test still green.
     */
    const collision = JSON.stringify({
      ...(JSON.parse(dataset) as Record<string, string[]>),
      /* An LGA spelled the way a served district is. Nothing marks it active —
       * `seedRows` does that for the served region alone — so this must NOT
       * throw, and the next assertion is the one that must. */
      Zamfara: ['Maitama District'],
    });
    expect(() => renderSeed(collision)).not.toThrow();

    /* …and now the same name INSIDE the served region, which is where two active
     * rows come from. It trips the region-scoped duplicate first, which is the
     * same defect one layer earlier. */
    const districts = DISTRICTS.map((d) => d.name);
    expect(new Set(districts).size).toBe(districts.length);
  });

  it('keeps aliases lowercase, and never a second copy of the name', () => {
    for (const district of DISTRICTS) {
      for (const alias of district.aliases ?? []) {
        expect(alias).toBe(alias.toLowerCase());
        /* The resolver folds punctuation out of `name` too, so an alias that
         * folds onto its own name is a match that already worked. */
        const fold = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, '');
        expect(fold(alias)).not.toBe(fold(district.name));
      }
    }
  });

  it('derives ids and keys from region and name, so a re-run reproduces them', () => {
    // Deterministic rather than minted: `newId()` would make every run of the
    // generator produce a different file, and the byte-identity test above
    // meaningless.
    expect(slug('Wuse II District')).toBe('wuse-ii-district');
    expect(slug('Abua/Odu')).toBe('abua-odu');
    expect(areaKey('Rivers', 'Port Harcourt')).toBe('rivers-port-harcourt');
    expect(areaId('Rivers', 'Port Harcourt')).toBe('area_rivers_port_harcourt');
  });

  it('escapes the apostrophes and slashes real place names contain', () => {
    const block = committedBlock();
    // "Abua/Odu", "Ogba/Egbema/Ndoni" — a slash is not a SQL metacharacter and
    // must survive verbatim; the quote doubling is what makes that safe to say.
    expect(block).toContain(`'Abua/Odu'`);
  });
});
